"""update datatype

Revision ID: a2f7e27bdda5
Revises: 93471e43672a
Create Date: 2024-04-15 16:35:45.381668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f7e27bdda5'
down_revision = '93471e43672a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
