"""role out for proyect

Revision ID: 172a2dc73add
Revises: 0340092a5586
Create Date: 2024-06-07 10:55:37.042196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172a2dc73add'
down_revision = '0340092a5586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=5, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
