"""authentication name

Revision ID: ec3cfcbf951b
Revises: a2f7e27bdda5
Create Date: 2024-04-17 09:27:20.794578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ec3cfcbf951b'
down_revision = 'a2f7e27bdda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenticated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_authenticate')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_authenticate', mssql.BIT(), autoincrement=False, nullable=False))
        batch_op.drop_column('active')
        batch_op.drop_column('authenticated')

    # ### end Alembic commands ###
